### ISSUE TITLE
Can't get 78% accuracy on restaurant dataset

### ISSUE THREAD

**Issue by Cppowboy** [lpq29743/IAN#3]
I ran this code on the restaurant dataset using the default parameter setting. However, the accuracy is only 69%. Can you figure out what's wrong?

**Comment by lpq29743** [comment]
Maybe you haven't taken a look on parameter settings in `main.py`, the default dataset is laptop dataset.

**Comment by lpq29743** [comment]
And there is a parameter called 'pre_processed' means whether you should preprocess the origin data files. If this parameter is set as 1, although you have changed the origin filenames, it still doesn't work.

**Comment by Cppowboy** [comment]
Thank you, it works!

**Comment by gliu9966** [comment]
> Thank you, it works!

How did you modify the code？

**Comment by Cppowboy** [comment]
> > Thank you, it works!
> 
> How did you modify the code？

Just set the pre_processed parameter to 0 when you are running the main.py script.

**Comment by gliu9966** [comment]
> Just set the pre_processed parameter to 0 when you are running the main.py script.

The accuracy remains the same when I set the pre_processed parameter to 0. Does this have anything to do with the equipment?
