### ISSUE TITLE
你好我有一点不明白的地方，想请教一下。

### ISSUE THREAD

**Issue by David931229** [lpq29743/IAN#4]
模型在test的时候，batch_size设置为len(data),这里data对于train_data和test_data来说都是tuple，其length都是5，不明白test的时候batch_size为什么设置成5。最后取平均的话，batch_size设置成什么结果应该都是一样的是吗？为什么不直接使用原来的batch_size128呢

**Comment by lpq29743** [comment]
Actually it's a bug. It should be `len(aspects)` rather than `len(data)`. Because the num of data is small, so we can feed it all to the model.
